name: ChunkaKit
author: Arhke
version: 1.0
main: net.waterraid.KitAbilities.Main
softdepend: [ArhkeLib,EssentialsSpawn,MoreFish,MythicMobs]
commands:
  armor:
    usage: /<command>
  ability:
    usage: /<command>
  effects:
    usage: /<command>
  pf:
    usage: /<command>
  potionfill:
    usage: /<command>
  weapon:
    usage: /<command>
